name: Deploy to Salesforce
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI with NPM
        run: |
          npm install @salesforce/cli --global

      - name: Install SFDX-Git-Delta
        run: |
          echo y | sf plugins install sfdx-git-delta

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.INTELOGIK_ORG_AUTH_URL }}" | sf org login sfdx-url --alias deployTest --set-default --sfdx-url-stdin

      - name: Generate Delta Manifest
        run: |
          sf sgd source delta --to "HEAD" --from "HEAD~1" --output-dir sgd-out --source-dir force-app

      - name: Deploy to Salesforce
        run: |
          sf project deploy start --manifest sgd-out/package/package.xml --target-org deployTest --wait 30