@isTest
public class MathOperationsTest 
{
@isTest
    public Static Void MyTest()
    {
        System.assertEquals (20, MathOperations.method1(10,10));
        System.assertEquals (200, MathOperations.method2(20,10));
        System.assertEquals (0, MathOperations.method3(10,10));
        System.assertEquals (1, MathOperations.method4(10,10));
        System.assertEquals ('Hi this is a String', MathOperations.method5('Hi this is a String'));
        
    }
    
}