public class MathOperations 
{
    Public Static Integer method1 (Integer x, Integer y) //10 ,10
    {
    Integer Z = X+y;
         Return Z;
    }
    Public Static Integer method2 (Integer x, Integer y) // 20 , 10
    {
        Integer Z = X*y;
         Return Z;
    }
    Public Static Integer method3 (Integer x, Integer y)
    {
        Integer Z = X-y;
        Return Z;
    }
    Public Static Integer method4 (Integer x, Integer y)
    {
        Integer Z = X/y;
         Return Z;
    }
     Public Static String method5 (String X)
    {
        Return X;
    }
}